### ISSUE TITLE
[BUG] Error when abort install of nighlty after error update to 4.1.0

### ISSUE THREAD

**Issue by sanjuant** [ThePorgs/Exegol#129]
### Describe the bug

Hello,

Today I saw the update to 4.1.0. I wanted to do the update as proposed by Exegol (I installed Exegol via the Github repo), but I had an error to retrieve the sources probably due to a DNS error on my side.

After it remained in 4.0.5 and I made an exegol update which proposed me to make the update of the nightly image. At that moment I accepted and then cancelled the nightly image update.

Since then, I have the following error: `/usr/bin/env: ‘python3\r’: No such file or directory`

I will try to reinstall Exegol, see if that fixes the problem and I will edit my post.

 Unfortunately, I did not capture all these steps. I'm on WSL2 Ubuntu 20.04 LTS with Windows 11

### Exegol Wrapper Version

```Text
❯ exegol version -vvv
/usr/bin/env: ‘python3\r’: No such file or directory
```
```


### Host OS

Windows 11

### Configuration of the concerned container

_No response_

### Execution logs in debug mode

```Text
❯ exegol version -vvv
/usr/bin/env: ‘python3\r’: No such file or directory
❯ exegol
/usr/bin/env: ‘python3\r’: No such file or directory
❯ exegol -h
/usr/bin/env: ‘python3\r’: No such file or directory
❯ exegol -debug
/usr/bin/env: ‘python3\r’: No such file or directory
❯ python3
Python 3.8.10 (default, Jun 22 2022, 20:18:18)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
```
```


### Exception

_No response_

### Anything else?

_No response_

**Comment by sanjuant** [comment]
Fixed with : `dos2unix exegol.py`

**Comment by Dramelac** [comment]
Hello,

It seems that during your git clone under Windows, it automatically changed the end of line in CRLF...
You can correct this by doing the git clone directly from your WSL or by modifying your git configuration on the windows repository: 
```
cd /path/to/Exegol
git config core.autocrlf false
```
If you have to modify manually, you can indeed use the `dos2unix` command but this command will modify the state of the file for git which could cause problems afterwards for the automatic update of the wrapper.

**Comment by sanjuant** [comment]
Thanks for your answer, after checking my git config file, the value was forced to true :/.
