### ISSUE TITLE
CI/CD pipeline (wrapper)

### ISSUE THREAD

**Issue by ShutdownRepo** [ThePorgs/Exegol#136]
Setup GitHub Actions workflows for building/packaging and pushing the wrapper code to PyPI

**Comment by Dramelac** [comment]
CI/CD are ready to test in dev branch.
Will be merge in master with the next wrapper release.

**Comment by Dramelac** [comment]
Merged in #152

**Comment by ShutdownRepo** [comment]
Approved with release 4.2.0 https://github.com/ThePorgs/Exegol/releases/tag/4.2.0
