### ISSUE TITLE
[BUG] Immediate error post install running 'exegol'. Docker connection aborted. Error while fetching server API version

### ISSUE THREAD

**Issue by reybango** [ThePorgs/Exegol#146]
### Describe the bug

After install I receive the following error when the 'exegol' command:
```
[-] Error while fetching server API version: ('Connection aborted.', PermissionError(13, 'Permission denied'))                                 
[!] Unable to connect to docker (from env config). Is docker operational and accessible? on your machine? Exiting.
```
I followed the steps here verbatim: https://exegol.readthedocs.io/en/latest/getting-started/install.html#installation-of-exegol

OS: Ubuntu 22.04.2 LTS with latest updates.
Python 3.10.6
pip 22.0.2 

```sudo docker run hello-world``` works fine. I followed the instructions ro run exegol from the user environment without sudo from the wiki and even tried the "dockerd-rootless-setuptool.sh install" command that comes after you install Docker to see if that would correct this issue.

### Steps To Reproduce

1. Following the install steps from here: https://exegol.readthedocs.io/en/latest/getting-started/install.html#installation-of-exegol
2. Type : ```exegol```

### Exegol Wrapper Version

```Text
This command doesn't work. 

I installed via pip and the latest version from PyPi is 4.1.1
```

### Host OS

Linux

### Execution logs in debug mode

```Text
The exegol command throws an error
```

**Comment by ShutdownRepo** [comment]
You're indicating `sudo docker run hello-world` works but `exegol` doesn't. Did you try `sudo exegol`?

**Comment by reybango** [comment]
@ShutdownRepo thanks for jumping in. Yeah I had tried that as well and I got ```sudo: exegol: command not found```. When I did ```sudo docker run hello-world``` it was only because that's what Docker said to do to test it. If I run ```docker run hello-world``` without sudo, it still works.

**Comment by reybango** [comment]
@ShutdownRepo the following seems to have fixed it:

1. ```sudo usermod -aG docker $USER```
2. ```newgrp docker```

That was from here: https://docs.docker.com/engine/install/linux-postinstall/#manage-docker-as-a-non-root-user

Slightly different than the instructions on the Exegol docs which are:
1.```sudo usermod -aG docker $(id -u -n)```
2.```newgrp```

**Comment by ShutdownRepo** [comment]
I updated the documentation accordingly: https://github.com/ThePorgs/Exegol-docs/commit/472b442e15018873b730151f361bb65859cc35da

**Comment by Abyss-W4tcher** [comment]
Hi, for anyone having this issue with docker rootless, you can apply the following patch to exegol :
```diff 
diff --git a/exegol/utils/DockerUtils.py b/exegol/utils/DockerUtils.py
index ae2752c..ccef46c 100644
--- a/exegol/utils/DockerUtils.py
+++ b/exegol/utils/DockerUtils.py
@@ -31,8 +31,8 @@ class DockerUtils:
     """Utility class between exegol and the Docker SDK"""
     try:
         # Connect Docker SDK to the local docker instance.
-        # Docker connection setting is loaded from the user environment variables.
-        __client: DockerClient = docker.from_env()
+        # Docker connection setting is loaded from the user docker socket (rootless).
+        __client: DockerClient = docker.DockerClient(base_url=f'unix://run/user/{os.getuid()}/docker.sock')
         # Check if the docker daemon is serving linux container
         __daemon_info = __client.info()
         if __daemon_info.get("OSType", "linux").lower() != "linux":
```

It won't use the "root" docker socket, but the one assigned to your user.

**Comment by AkechiShiro** [comment]
Hey @ShutdownRepo is there any way this patch could land in the repo ?

Should I PR or perhaps @Abyss-W4tcher you might want to PR it, since you're the author, I guess ?

**Comment by ShutdownRepo** [comment]
Hmm, any insight on this @Dramelac?

**Comment by Dramelac** [comment]
The rootless limitation is not just about the socket path, there is some limitation that could affect exegol UX cf: https://docs.docker.com/engine/security/rootless/#known-limitations
However, docker has made good progress recently, and when the limitations are no longer a blocking factor, we'll be able to test it.
