### ISSUE TITLE
[BUG] Pip install not working on Ubuntu 23.04

### ISSUE THREAD

**Issue by Nariod** [ThePorgs/Exegol#160]
### Describe the bug

Following the documentation, I am trying to install Exegol using pip which fails with the error `error: externally-managed-environment`. The result is the same with either `sudo` or not.

### Steps To Reproduce

On a Ubuntu 23.04 system: 
1. Run `python3 -m pip install exegol`
![image](https://github.com/ThePorgs/Exegol/assets/32550820/5f2455e1-299b-4803-af75-8c0ad2d7cb7c)

2. Run `sudo python3 -m pip install exegol`
![image](https://github.com/ThePorgs/Exegol/assets/32550820/76926743-fe7d-4a9c-80a2-81957b2b968c)

3. Run `sudo python3 -m pip install --requirement "Exegol/requirements.txt"`
![image](https://github.com/ThePorgs/Exegol/assets/32550820/72748080-9446-466e-9688-4ae3d9943be0)

### Exegol Wrapper Version

```Text
N/A
```

### Host OS

Linux

### Execution logs in debug mode

```Text
N/A
```

**Comment by Dramelac** [comment]
Hello

What is your version of python and how did you installed python on your OS ? It seems like your python setup is broken :/

Do you have the same error when installing other package ?

Do you have multiple python version installed ? (To avoid conflict beetwen them)

**Comment by Nariod** [comment]
Hello @Dramelac,

This behavior happened after an upgrade from Ubuntu 22.10 to 23.04. The python version is 3.11.2, however there is indeed a problem on my installation, as I get the same error message for all pip packet installs.

**Comment by Nariod** [comment]
Closing the issue, as it is more related to an Ubuntu upgrade issue than Exegol.
