### ISSUE TITLE
Request to add a --run-script option for post install setup

### ISSUE THREAD

**Issue by M-Davies** [ThePorgs/Exegol#186]
### The needs

I would like a command line option for `exegol start` (possibly called `--run-script`, `--run`, etc) where you can specifiy a list of shell commands (or a .sh file) that will run on the container once it has booted up. This would help with setting up additional users, tooling, environments, etc.

### Description

Long time user (thanks for this project 🙂), I would defintely find this useful in the more hardened environments I test on.

Cause of the hardened environments, I usually need to transfer CA certificates across to the container, install them, set up users and firewall rules, etc which is a pain to do everytime. I would like a command line option that allows you to specify a script file and/or list of commands that does this setup for me. It could look something like this:

*/my/workspace/path/script.sh*
```shell
#!/bin/bash
useradd -m myuser
usermod -aG sudo myuser
apt-get install sshuttle
```
And then:
```shell
exegol start -w /my/workspace/path --run-script /my/workspace/path/script.sh myexegolcontainer full
```

### Alternatives

Simply putting a `.sh` file in the specified workspace directory and running that. This also works but it would be nice if the container would have it all installed once it's started up and I can just get going with testing.

**Comment by ShutdownRepo** [comment]
Hey there, take a look at my-resources' user setup, I think it answers 100% your need https://exegol.readthedocs.io/en/latest/exegol-image/my-resources.html#user-setup

**Comment by M-Davies** [comment]
Ah cheers, this is perfect for my needs
