### ISSUE TITLE
Upgrade of Wrapper v4.3.1 -> v4.3.2 on MacOS occurs a CRITICAL ERROR 

### ISSUE THREAD

**Issue by yanisAlb00** [ThePorgs/Exegol#214]
### Describe the bug

Hello,

I have the following CRITICAL Error when I type yes to confirm Exegol Wrapper Upgrade from 4.3.1 to 4.3.2 on MacOS :

exegol info
/Library/Python/3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
[*] Exegol is currently in version v4.3.1
[*] Exegol Discord serv.: https://discord.gg/cXThyp7D6P
[*] Exegol documentation: https://exegol.rtfd.io/
[+] We thank Capgemini for supporting the project (helping with dev) 🙏                                                                                                                                   
[+] We thank HackTheBox for sponsoring the multi-arch support 💚                                                                                                                                          

[?] An Exegol update is available (v4.3.1 -> v4.3.2), do you want to update ? [Y/n]: Y
[*] Updating Exegol wrapper source code                                                                                                                                                                   
[*] Using branch master on wrapper repository                                                                                                                                                             
[-] It seems that something unexpected happened ...                                                                                                                                                       
[-] To draw our attention to the problem and allow us to fix it, you can share your error with us (by copying and pasting it with this syntax: ``` <error> ```) by creating a GitHub issue at this        
address: https://github.com/ThePorgs/Exegol/issues                                                                                                                                                        
[+] Thank you for your collaboration!                                                                                                                                                                     
[!] A critical error occurred while running this git command: git pull -v -- origin master => Your local changes to the following files would be overwritten by merge:  

### Steps To Reproduce

MacOS Sonoma Version 14.4.1 (23E224) with Docker Desktop to run containers

### Exegol Wrapper Version

```Text
exegol version -vvv

/Library/Python/3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
[*] Exegol is currently in version v4.3.1
[*] Exegol Discord serv.: https://discord.gg/cXThyp7D6P
[*] Exegol documentation: https://exegol.rtfd.io/
[+] We thank Capgemini for supporting the project (helping with dev) 🙏                                                                                                                                   
[+] We thank HackTheBox for sponsoring the multi-arch support 💚                                                                                                                                          
[D] Pip installation: Off 🪓                                                                                                                                                                              
[D] Git source installation: On ✔                                                                                                                                                                         
[D] Host OS: Mac (Docker desktop)                                                                                                                                                                         
[D] Arch: arm64                                                                                                                                                                                           
[D] Docker desktop: On ✔                                                                                                                                                                                  
[D] Shell type: Mac                                                                                                                                                                                       

[?] An Exegol update is available (v4.3.1 -> v4.3.2), do you want to update ? [Y/n]: n
```

### Host OS

None

### Execution logs in debug mode

```Text
exegol info
/Library/Python/3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
[*] Exegol is currently in version v4.3.1
[*] Exegol Discord serv.: https://discord.gg/cXThyp7D6P
[*] Exegol documentation: https://exegol.rtfd.io/
[+] We thank Capgemini for supporting the project (helping with dev) 🙏                                                                                                                                   
[+] We thank HackTheBox for sponsoring the multi-arch support 💚                                                                                                                                          

[?] An Exegol update is available (v4.3.1 -> v4.3.2), do you want to update ? [Y/n]: Y
[*] Updating Exegol wrapper source code                                                                                                                                                                   
[*] Using branch master on wrapper repository                                                                                                                                                             
[-] It seems that something unexpected happened ...                                                                                                                                                       
[-] To draw our attention to the problem and allow us to fix it, you can share your error with us (by copying and pasting it with this syntax:  <error> ```) by creating a GitHub issue at this        
address: https://github.com/ThePorgs/Exegol/issues                                                                                                                                                        
[+] Thank you for your collaboration!                                                                                                                                                                     
[!] A critical error occurred while running this git command: git pull -v -- origin master => Your local changes to the following files would be overwritten by merge:
```

**Comment by Dramelac** [comment]
Hello @yanisAlb00 

It seems you have locally updated some file on your local repository. Try to discard them before updating.
To see them, run `git status` in your Exegol folder. Then, you can run `git restore <file>`.

If that's not the case, try to run the command supplied by exegol `git pull -v -- origin master` and paste the output here so i can help you debug.

**Comment by ShutdownRepo** [comment]
Closing the issue and replacing the "bug" tag with an "invalid" tag as I think this is issue is not related to Exegol directly but as Dramelac said, to some local files that were modified before the update attempt. 
@yanisAlb00 if the issue persists, don't hesitate to re-open this thread 🙂

**Comment by yanisAlb00** [comment]
Thanks @Dramelac @ShutdownRepo the upgrade works well after I pulled last version of the repo on my local git
