### ISSUE TITLE
Add device /dev/net/tun for Docker Desktop

### ISSUE THREAD

**Issue by exil-security** [ThePorgs/Exegol#225]
### The needs

The device /dev/net/tun can be pass through using the option --vpn but not using the --device directly using Docker Desktop on MacOS.

![image](https://github.com/ThePorgs/Exegol/assets/36631807/3b1254dc-f1ba-444c-ac16-b89d8074188b)

### Description

We can add filter to allow this device /dev/net/tun on addUserDevice function to allow this device.

File: exegol/model/ContainerConfig.py
```python
<SNIP>
def addUserDevice(self, user_device_config: str):
        """Add a device from a user parameters"""
        if EnvInfo.isDockerDesktop() and user_device_config != "/dev/net/tun" :
            logger.warning("Docker desktop (Windows & macOS) does not support USB device passthrough.")
            logger.verbose("Official doc: https://docs.docker.com/desktop/faqs/#can-i-pass-through-a-usb-device-to-a-container")
            logger.critical("Device configuration cannot be applied, aborting operation.")
        self.__addDevice(user_device_config)
<SNIP>
```

Adding fillter can fix the problem for the /dev/net/tun and still abort in case of other device like usb 

![image](https://github.com/ThePorgs/Exegol/assets/36631807/9c44d62a-6dd0-4e85-a200-c98708d4a808)

### Alternatives

Maybe create a whitelist of working devices on Docker Desktop on the future in order to allow the --device option for those devices

**Comment by Dramelac** [comment]
Suggested fix: https://github.com/ThePorgs/Exegol/issues/225
